name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  scan_ruby:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set execute permissions for brakeman
        run: chmod +x bin/brakeman

      - name: Run Brakeman
        run: bin/brakeman --no-pager || true

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: false  # 关闭缓存以确保新版本生效

      - name: Fix permissions
        run: chmod +x bin/*

      - name: Upgrade RubyGems and Bundler
        run: |
          gem update --system
          gem install bundler

      - name: Install dependencies
        run: bundle install

      - name: Scan for common Rails security vulnerabilities using static analysis
        run: bin/brakeman --no-pager

  scan_js:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: false

      - name: Fix permissions
        run: chmod +x bin/*

      - name: Upgrade RubyGems and Bundler
        run: |
          gem update --system
          gem install bundler

      - name: Install dependencies
        run: bundle install

      - name: Scan for security vulnerabilities in JavaScript dependencies
        run: bin/importmap audit

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: false

      - name: Fix permissions
        run: chmod +x bin/*

      - name: Upgrade RubyGems and Bundler
        run: |
          gem update --system
          gem install bundler

      - name: Install dependencies
        run: bundle install

      - name: Lint code for consistent style
        run: bin/rubocop -f github

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Install packages
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y google-chrome-stable curl libjemalloc2 libvips sqlite3

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: false

      - name: Fix permissions
        run: chmod +x bin/*

      - name: Upgrade RubyGems and Bundler
        run: |
          gem update --system
          gem install bundler

      - name: Install dependencies
        run: bundle install

      - name: Ensure Rails scripts have execute permissions
        run: chmod +x bin/rails

      - name: Run tests
        env:
          RAILS_ENV: test
        run: bin/rails db:test:prepare test test:system

      - name: Keep screenshots from failed system tests
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: screenshots
          path: ${{ github.workspace }}/tmp/screenshots
          if-no-files-found: ignore